apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec: 
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx-development


