apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-web-deployment
  labels:
    app: django-k8s-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-k8s-web-deployment
  template:
    metadata:
      labels:
        app: django-k8s-web-deployment
    spec:
      containers:
      - name: django-k8s-web
        image: registry.digitalocean.com/imk-k8s/django-k8s-web:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef: 
              name: django-k8s-web-prod-env
        env: 
          - name: PORT
            value: "8003"
        ports:
        - containerPort: 8003
      imagePullSecrets:
        - name: imk-k8s

---

apiVersion: v1
kind: Service
metadata:
  name: django-k8s-web-service
spec: 
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8003
  selector:
    app: django-k8s-web-deployment
